### ISSUE TITLE
File not uploaded to Internet Archive if bucket was previously created

### ISSUE THREAD

**Issue by jbothma** [mfmamirror/mfmacrawl#1]
```
2019-05-24 20:47:27 [scrapy.core.scraper] ERROR: Error processing {'original_url': u'http://mfma.treasury.gov.za/RegulationsandGazettes/MunicipalRegulationsOnAStandardChartOfAccountsFinal/Documents/Reporting%20Reference%20Group/03.%2013%20June%202017/Layout%20and%20dropdown%20examples/Muncde_2017_BMQ1.txt',
 'path': u'/RegulationsandGazettes/MunicipalRegulationsOnAStandardChartOfAccountsFinal/Documents/Reporting Reference Group/03. 13 June 2017/Layout and dropdown examples/Muncde_2017_BMQ1.txt',
 'type': 'file'}
Traceback (most recent call last):
  File "/home/pi/mfmamirror/mfmacrawl/env/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/pi/mfmamirror/mfmacrawl/mfma/pipelines.py", line 178, in process_item
    bucket = self.conn.create_bucket(identifier, headers=headers)
  File "/home/pi/mfmamirror/mfmacrawl/env/local/lib/python2.7/site-packages/boto/s3/connection.py", line 620, in create_bucket
    response.status, response.reason, body)
S3CreateError: S3CreateError: 409 Conflict
<?xml version='1.0' encoding='UTF-8'?>
<Error><Code>BucketAlreadyExists</Code><Message>The requested bucket name is not available. The bucket namespace is shared by all users of the system. Please select a different name and try again.</Message><Resource /><RequestId>1408a4e2-e6b6-4463-b9b7-629e9f138738</RequestId></Error>
```

https://github.com/mfmamirror/mfmacrawl/blob/master/mfma/pipelines.py#L178

Solution is probable to check for existing bucket and only try to create if it doesn't exist or to catch BucketAlreadyExists and then upload.

**Comment by jbothma** [comment]
Bucket without file https://archive.org/details/ocuments_reporting_reference_group_03_13_june_2017_layout_and_dropdown_examples_muncde_2017_bmq1_txt

**Comment by jbothma** [comment]
Similar bucket incl fie https://archive.org/details/l_documents_reporting_reference_group_13_june_2017_layout_and_dropdown_examples_muncde_2017_bmq1_txt
